# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0002_auto_20180324_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 12, 21, 377851)),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 12, 21, 374712)),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'495a30c7-43d9-4bba-9555-77b3819a458a', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 12, 21, 375998)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 12, 21, 377342)),
        ),
    ]
