# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0003_auto_20180324_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 30, 52, 655096)),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 30, 52, 652047)),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'c1317ff4-676d-44a1-9d60-0b51df4d12b3', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 30, 52, 653272)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 30, 52, 654595)),
        ),
    ]
