# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0004_auto_20180324_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 15, 518845)),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 15, 515794)),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'21abaabb-103a-48a9-9652-1f0fdb58e801', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 15, 517021)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 15, 518343)),
        ),
    ]
