# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0005_auto_20180324_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingentry',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 48, 628099)),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 48, 624941)),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'76cf38c9-fb2f-495e-a1e0-81cc05c8558d', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 48, 626225)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 9, 32, 48, 627556)),
        ),
    ]
